services:
  nestjs-app:
    container_name: nestjs-app-task-container
    build:
      context: .
      dockerfile: Dockerfile
    image: firashusawi/nestjs-app-task:v1.17.0
    ports:
      - '3000:3000'
    volumes:
      - .:/dist
    command: node main.js
